apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-management
  template:
    metadata:
      labels:
        app: employee-management
    spec:
      containers:
      - image: ghcr.io/tungphuong/employee-management.api:latast
        name: employee-management
        ports:
          - containerPort: 5102