apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

commonLabels:
  env: dev

images:
  - name: ghcr.io/tungphuong/admin.api
    newTag: 6eb719a
