apiVersion: v1
kind: Service
metadata:
  name: mailserver
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 25
      targetPort: 25
      protocol: TCP
      name: smtp  
