name: Communication pipeline
on:
  push:
    branches:
    - main
    - feature/**
    
    paths:
    - communication/**
    - .github/workflows/communication-pipeline.yml
  
  pull_request:
    branches:
    - main
    
    paths:
    - communication/**
    - .github/workflows/communication-pipeline.yml

env:
  DOTNET_VERSION: 6.0.x
  IMAGE: communication.api
  REGISTRY: ghcr.io

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3            
      
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      
      - name: Build
        run: |
          cd communication
          mkdir ./publish
          go mod download
          go build -o ./publish/communication           
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{github.repository_owner}}/${{ env.IMAGE }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short
            type=raw,value=latest

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with: 
          context: ./communication
          file: ./communication/Dockerfile.ci
          push: true
          tags: ${{ steps.meta.outputs.tags }}             
          labels: ${{ steps.meta.outputs.labels }}