name: Employee Management pipeline
on:
  push:
    branches:
    - main
    
    paths:
    - employee-management/**
    - building-blocks/**
    - .github/workflows/employee-pipeline.yml
  
  pull_request:
    branches:
    - main
    
    paths:
    - employee-management/**
    - building-blocks/**
    - .github/workflows/employee-pipeline.yml

env:
  DOTNET_VERSION: 6.0.x
  IMAGE: employee-management.api
  REGISTRY: ghcr.io

jobs:
  BuildLinux:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: false
      
      - name: Build
        run: |
          cd employee-management/EmployeeManagement.Api
          mkdir ./publish
          dotnet restore EmployeeManagement.Api.csproj
          dotnet publish --no-restore "EmployeeManagement.Api.csproj" -c Release -o ./publish          
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: ${{ env.REGISTRY }}/${{github.repository_owner}}/${{ env.IMAGE }}
          flavor: |
            latest=auto
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=short

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}      

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with: 
          context: ./employee-management/EmployeeManagement.Api
          file: ./employee-management/EmployeeManagement.Api/Dockerfile.ci
          push: true
          tags: ${{ steps.meta.outputs.tags }}             
          labels: ${{ steps.meta.outputs.labels }}